---
Name: webpsubstitution
---
QuinnInteractive\WebPSub\Task\ConvertImagesToWebpTask:
  webp_directory_name: '.webp'
  webp_file_suffix: '.webp'
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - QuinnInteractive\WebPSub\Extension\DBFileExtension
